name: slp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0
  - python=3.7
  - pytorch
  - torchvision
  - visdom
  - jupyter
  - scipy  
  - matplotlib
  - h5py
  - pip
  - pip:
    - pysimplegui
    - torch-summary
    - opencv-python
    - imageio